services:
  service:
    build:
      context: .
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider localhost:8080/health || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 20s
    depends_on:
      - db
    environment:
      APP_NAME: "berte-service"
      DB_HOST: "db"
    ports:
      - "8080:8080"

  db:
    image: postgres:16.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: berte_service
      POSTGRES_USER: berte_service
      POSTGRES_DB: berte_service

volumes:
  pg_data: { }
