ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ru.somarov.berte.infrastructure.config.ApplicationConfigKt.config
  name: "$APP_NAME:berte-service"
  instance: "$HOSTNAME:undefined"
  db:
    host: "$DB_HOST:localhost"
    port: "$DB_PORT:5432"
    name: "$DB_NAME:berte_service"
    schema: "$DB_SCHEMA:berte_service"
    user: "$DB_USER:berte_service"
    password: "$DB_PASSWORD:berte_service"
    connection-timeout: "$DB_CONNECTION_TIMEOUT:PT5S"
    statement-timeout: "$DB_STATEMENT_TIMEOUT:PT5S"
    pool:
      max-size: "$DB_POOL_MAX_SIZE:8"
      min-idle: "$DB_POOL_MIN_IDLE:2"
      max-idle-time: "$DB_POOL_MAX_IDLE_TIME:PT1M"
      max-life-time: "$DB_POOL_MAX_LIFE_TIME:PT1M"
      validation-query: "$DB_POOL_VALIDATION_QUERY:SELECT 1"
  kafka:
    brokers: "$KAFKA_BROKERS:localhost:9092"
    producers:
      retry:
        enabled: "$KAFKA_RETRY_PRODUCING_ENABLED:false"
        topic: "berte_service_retry"
        max-in-flight: "1"
      dlq:
        enabled: "$KAFKA_RETRY_DLQ_ENABLED:false"
        topic: "berte_service_dlq"
        max-in-flight: "1"
  otel:
    protocol: "http"
    host: "$OTEL_HOST:localhost"
    logs-port: "4317"
    metrics-port: "4318"
    tracing-port: "4319"
    tracing-probability: "1.0"