receivers:
  otlp/logs:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  otlp/metrics:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

  otlp/traces:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4319

exporters:
  otlp/logs:
    endpoint: dataprepper:4317
    tls:
      insecure: true
  otlp/metrics:
    endpoint: dataprepper:4318
    tls:
      insecure: true
  otlp/traces:
    endpoint: dataprepper:4319
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [ otlp/metrics ]
      exporters: [ otlp/metrics ]
    logs:
      receivers: [ otlp/logs ]
      exporters: [ otlp/logs ]
    traces:
      receivers: [ otlp/traces ]
      exporters: [ otlp/traces ]
